  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_joint
    pid: {p: 0.1, i: 0.01, d: 0.01}
